# Generated by Django 6.1.1 on 2026-09-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
