# Generated by Django 6.1.1 on 2026-09-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_detail', models.CharField(blank=True, help_text="e.g. company name, or 'Homeowner, Kicukiro'", max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text="1–5 stars. Leave at 5 if you don't want to bother tracking this.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('general', 'General work')], default='general', max_length=10)),
                ('pair_key', models.CharField(blank=True, help_text="Optional. Give a 'before' and an 'after' photo the same pair_key (e.g. 'office-oct-2026') to link them as a before/after set.", max_length=60)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
