# Generated by Django 6.1.1 on 2026-09-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_workphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional. A photo of the client, or their company logo — shown next to the quote if provided.', null=True, upload_to='testimonials/'),
        ),
    ]
