"""
Django settings for lamar_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#
# Locally, this falls back to a dev-only key so `runserver` works out of the
# box. In production, set a real DJANGO_SECRET_KEY environment variable —
# generate one with:
#   python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-zof1ta*d%we*71-3dji3s-@t*kyexxqjn#drsu=5tfk!6#i=ym',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development. In production, set:
#   DJANGO_DEBUG=False
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Refuse to start in production with the built-in development key.
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'Set a real DJANGO_SECRET_KEY environment variable when DJANGO_DEBUG=False.'
    )

# Comma-separated list of allowed hostnames, e.g.:
#   DJANGO_ALLOWED_HOSTS=lamarinvestment.rw,www.lamarinvestment.rw
_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]

# Railway sets these automatically for the service.
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if _railway_domain and _railway_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_railway_domain)
# Folder of the Railway Volume (permanent disk), if one is attached.
RAILWAY_VOLUME = os.environ.get('RAILWAY_VOLUME_MOUNT_PATH', '')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves /static/ in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lamar_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.analytics',
            ],
        },
    },
]

WSGI_APPLICATION = 'lamar_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # On a server, point DJANGO_DB_PATH at a folder that survives redeploys,
        # e.g. /var/lib/lamar/db.sqlite3
        'NAME': os.environ.get(
            'DJANGO_DB_PATH',
            os.path.join(RAILWAY_VOLUME, 'db.sqlite3') if RAILWAY_VOLUME else BASE_DIR / 'db.sqlite3',
        ),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Kigali'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Photos uploaded through the admin (team, partners, materials, Our Work).
# On a server, point DJANGO_MEDIA_ROOT at a folder that survives redeploys.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get(
    'DJANGO_MEDIA_ROOT',
    os.path.join(RAILWAY_VOLUME, 'media') if RAILWAY_VOLUME else BASE_DIR / 'media',
)

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Defaults to printing emails to the console (dev-friendly, zero setup).
# For production, set these environment variables to use real SMTP, e.g. Gmail:
#   EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=your-address@gmail.com
#   EMAIL_HOST_PASSWORD=your-app-password
#   DEFAULT_FROM_EMAIL=info@lamarinvestment.rw
#   LAMAR_NOTIFY_EMAIL=info@lamarinvestment.rw

# Resend (HTTPS API) is used automatically when RESEND_API_KEY is set - required on
# Railway's non-Pro plans, where SMTP is blocked. Otherwise: SMTP if EMAIL_BACKEND
# says so, or print to the console for local development.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'core.email_backends.ResendEmailBackend' if RESEND_API_KEY
    else 'django.core.mail.backends.console.EmailBackend',
)
EMAIL_TIMEOUT = 10  # seconds - never let a slow mail server hang the contact form
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Lamar Investment <info@lamarinvestment.rw>')

# Where new inquiry notifications are sent
LAMAR_NOTIFY_EMAIL = os.environ.get('LAMAR_NOTIFY_EMAIL', 'info@lamarinvestment.rw')

# Google Analytics (GA4)
# Empty by default — analytics only load once a real Measurement ID is set.
# Get one at analytics.google.com (Admin > Data Streams > your web stream),
# it looks like "G-XXXXXXXXXX". Then set:
#   GOOGLE_ANALYTICS_ID=G-XXXXXXXXXX
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID', '')


# Admin dashboard theme (django-jazzmin)
# https://django-jazzmin.readthedocs.io/

JAZZMIN_SETTINGS = {
    "site_title": "Lamar Admin",
    "site_header": "Lamar Investment",
    "site_brand": "Lamar Investment Co.",
    "site_logo": "core/img/favicon.png",
    "login_logo": "core/img/logo-stacked.png",
    "site_icon": "core/img/favicon.png",
    "welcome_sign": "Welcome to the Lamar Investment Company dashboard",
    "copyright": "Lamar Investment Company Ltd",
    "search_model": ["core.Inquiry", "core.TeamMember", "core.Partner"],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Inquiry": "fas fa-envelope-open-text",
        "core.Partner": "fas fa-handshake",
        "core.TeamMember": "fas fa-user-tie",
        "core.Testimonial": "fas fa-quote-right",
        "core.WorkPhoto": "fas fa-images",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "order_with_respect_to": [
        "core.Inquiry",
        "core.TeamMember",
        "core.Partner",
        "core.Testimonial",
        "core.WorkPhoto",
        "auth",
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
        {"model": "core.Inquiry"},
    ],

    "custom_css": "core/css/admin-theme.css",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",

    # Replaces the old JAZZMIN_UI_TWEAKS["dark_mode_theme"] (now deprecated —
    # every theme supports light/dark via data-bs-theme). "light" keeps the
    # previous fixed-light behaviour; use "auto" to follow the admin user's
    # OS/browser preference instead, or "dark" to force dark mode.
    "default_theme_mode": "light",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-success",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


# Production security hardening
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# These only take effect once DEBUG=False (i.e. in production). They assume
# the site is served over HTTPS, which any real host should provide.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week to start; raise once confident
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    # If ALLOWED_HOSTS includes your real domain, also trust it for CSRF
    # (required by Django for POST requests, e.g. the contact form) over HTTPS:
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host]

    # Behind Nginx / a hosting platform's proxy, Django only knows the request
    # was HTTPS if the proxy says so. Without this the HTTPS redirect loops.
    # Set DJANGO_BEHIND_PROXY=False only if gunicorn is exposed directly.
    if os.environ.get('DJANGO_BEHIND_PROXY', 'True') == 'True':
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Log errors to the console so they show up in `journalctl` / the host's log viewer.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {'django': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False}},
}
